[phases.setup]
nixPkgs = ["python312", "gcc"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --user uv",
  "cd apps/api && $HOME/.local/bin/uv sync --frozen"
]

[phases.build]
cmds = ["echo build-phase noop"]

[start]
cmd = "cd apps/api && $HOME/.local/bin/uv run gunicorn --bind 0.0.0.0:$PORT --workers 2 --access-logfile - 'redbull_api.app:create_app()'"
